<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class contentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $content =
        [
            [
                'tabs' => 1,
                'title' => 'Programming Languages & Tools',
                'sub_title' => null,
                'description' => null,
                'from' => null,
                'to' => null,
                'link' => null,
                'deleted' => null,
                'updated' => null,
                'list_title' => null,
            ],
            [
                'tabs' => 1,
                'title' => 'Other languages',
                'sub_title' => null,
                'description' => null,
                'from' => null,
                'to' => null,
                'link' => null,
                'deleted' => null,
                'updated' => null,
                'list_title' => null,
            ],
            [
                'tabs' => 1,
                'title' => 'Other libraries',
                'sub_title' => null,
                'description' => null,
                'from' => null,
                'to' => null,
                'link' => null,
                'deleted' => null,
                'updated' => null,
                'list_title' => null,
            ],
            [
                'tabs' => 1,
                'title' => 'Frameworks',
                'sub_title' => null,
                'description' => null,
                'from' => null,
                'to' => null,
                'link' => null,
                'deleted' => null,
                'updated' => null,
                'list_title' => null,
            ],
            [
                'tabs' => 1,
                'title' => 'Server-management',
                'sub_title' => null,
                'description' => null,
                'from' => null,
                'to' => null,
                'link' => null,
                'deleted' => null,
                'updated' => null,
                'list_title' => null,
            ],
            [
                'tabs' => 1,
                'title' => 'Workflow',
                'sub_title' => null,
                'description' => null,
                'from' => null,
                'to' => null,
                'link' => null,
                'deleted' => null,
                'updated' => null,
                'list_title' => null,
            ],
            [
                'tabs' => 2,
                'title' => 'About me',
                'sub_title' => null,
                'description' => null,
                'from' => null,
                'to' => null,
                'link' => null,
                'deleted' => null,
                'updated' => null,
                'list_title' => null,
            ],
            [
                'tabs' => 3,
                'title' => 'Junior Software Developer',
                'sub_title' => 'Future of Finance',
                'description' => 'My work here is to primarly add to an existing workflow application called Finly. This workflow application allows financial advisors to work more efficiently and faster. It also makes it easier for the advisor to work from home. At Future of finance we also have other software than just a workflow application, we have our own custom made API and other applications that work with the workflow application such as hypotheek.nl. For more information about what we do, go to https://www.getfinly.com/',
                'from' => 'july 2021',
                'to' => 'present',
                'link' => null,
                'deleted' => null,
                'updated' => null,
                'list_title' => null,
            ],
            [
                'tabs' => 3,
                'title' => 'Web developer',
                'sub_title' => 'Stenniz Music',
                'description' => 'During my second year of school, I got an interinship at Stenniz Music. My job was to create a commercial viable website to promote the workshops the company provided',
                'from' => 'August 2020',
                'to' => 'January 2021',
                'link' => null,
                'deleted' => null,
                'updated' => null,
                'list_title' => null,
            ],
            [
                'tabs' => 3,
                'title' => 'Deliverer',
                'sub_title' => 'Wit-lof',
                'description' => "My primary job here is to deliver food too your doorstep. I mostly deliver with a moped but also sometimes with the car. At times when it's not busy I help around in the kitchen",
                'from' => 'January 2019',
                'to' => 'August 2021',
                'link' => null,
                'deleted' => null,
                'updated' => null,
                'list_title' => null,
            ],
            [
                'tabs' => 3,
                'title' => 'Technician',
                'sub_title' => 'Stedin',
                'description' => "At stedin I followed an internship to become electrician. I worked all over the infastructure, from your fuse box to to kabels running underground. I placed, repaired electrical cabels and fuse boxes",
                'from' => 'August 2018',
                'to' => 'August 2019',
                'link' => null,
                'deleted' => null,
                'updated' => null,
                'list_title' => null,
            ],
            [
                'tabs' => 3,
                'title' => 'Technician',
                'sub_title' => 'Stedin',
                'description' => "At stedin I followed an internship to become electrician. I worked all over the infastructure, from your fuse box to to kabels running underground. I placed, repaired electrical cabels and fuse boxes",
                'from' => 'August 2018',
                'to' => 'August 2019',
                'link' => null,
                'deleted' => null,
                'updated' => null,
                'list_title' => null,
            ],
            [
                'tabs' => 3,
                'title' => 'Technician',
                'sub_title' => 'Stedin',
                'description' => "At stedin I followed an internship to become electrician. I worked all over the infastructure, from your fuse box to to kabels running underground. I placed, repaired electrical cabels and fuse boxes",
                'from' => 'August 2018',
                'to' => 'August 2019',
                'link' => null,
                'deleted' => null,
                'updated' => null,
                'list_title' => null,
            ],
            [
                'tabs' => 3,
                'title' => 'Service Staff',
                'sub_title' => 'Shell',
                'description' => "At shell I mostly ran as a cashier, but other times when there were extra co-workers around I'd help clean up the gas station.",
                'from' => 'January 2019',
                'to' => 'juli 2019',
                'link' => null,
                'deleted' => null,
                'updated' => null,
                'list_title' => null,
            ],
            [
                'tabs' => 4,
                'title' => 'ICT Campus',
                'sub_title' => 'MBO-4',
                'description' => null,
                'from' => 'August 2019',
                'to' => 'Present',
                'link' => null,
                'deleted' => null,
                'updated' => null,
                'list_title' => null,
            ],
            [
                'tabs' => 4,
                'title' => 'Werk en Vakmanschap & Stedin',
                'sub_title' => 'MBO-2',
                'description' => null,
                'from' => 'August 2018',
                'to' => 'june 2019',
                'link' => null,
                'deleted' => null,
                'updated' => null,
                'list_title' => null,
            ],
            [
                'tabs' => 4,
                'title' => 'Axia College',
                'sub_title' => 'VMBO-TL',
                'description' => null,
                'from' => 'August 2017',
                'to' => 'August 2018',
                'link' => null,
                'deleted' => null,
                'updated' => null,
                'list_title' => null,
            ],
            [
                'tabs' => 5,
                'title' => null,
                'sub_title' => null,
                'description' => "Apart from being a web developer, I enjoy most of my time inside. Doesn't mean I'm an caveman, just a programmer. In the weekends I like to spend time with friends. During school weeks I like to spend my time playing games or watching movies. I also go to the gym twice a week, got to train the body as much as the mind! At other times, I really enjoy cooking. I always like an enjoyable meal after a hard days work. I also like to continue developing my programming skills and learn new things",
                'from' => null,
                'to' => null,
                'link' => null,
                'deleted' => null,
                'updated' => null,
                'list_title' => null,
            ],
            [
                'tabs' => 6,
                'title' => "Stennizworkshops.nl",
                'sub_title' => "stennizworkshops",
                'description' => "During my first interinship in my second year i develop a commercial website. With this website schools and buisnesses can choose from many different workshops they want to give at their school or buisness.",
                'from' => null,
                'to' => null,
                'link' => "Github: https://github.com/JarodIking/stennizworkshops",
                'deleted' => null,
                'updated' => null,
                'list_title' => null,
            ],
            [
                'tabs' => 6,
                'title' => "50plusroadtrips.nl",
                'sub_title' => "50plusroadtrip",
                'description' => "During my second year I'm develop a website where people can register for roadtrips, this website is going to be expanded. This website is even running on my own server!",
                'from' => null,
                'to' => null,
                'link' => "Github: https://github.com/JarodIking/Road-trip-50--website",
                'deleted' => null,
                'updated' => null,
                'list_title' => null,
            ],
            [
                'tabs' => 6,
                'title' => "Jarodiking.com",
                'sub_title' => "jarodiking",
                'description' => "During my second year I developed a site to promote myself as a programmer. With this website I want to display all my skills as a programmer and add anything new that I learn. This website is running on my own server to!",
                'from' => null,
                'to' => null,
                'link' => "Github: https://github.com/JarodIking/portfolio",
                'deleted' => null,
                'updated' => null,
                'list_title' => null,
            ],
            [
                'tabs' => 7,
                'title' => "The Invaders",
                'sub_title' => "C++",
                'description' => "This C++ game is a project I made for my exams. It took some time to make, but I'm happy I made it because it gave me a really good score When you start this game you'll see a row of invaders that will shoot at you. It is your job to shoot these invaders and win the day. When you have shot all the invader you'll advance to the next level. Each level you advance, the game will get harder and harder. There will be more aliens and the aliens will shoot more and more. Make sure you dont die and that the aliens dont reach you!",
                'from' => null,
                'to' => null,
                'link' => "Github link: https://github.com/JarodIking/Game-C-",
                'deleted' => null,
                'updated' => null,
                'list_title' => "Requirements",
            ],

        ];

        foreach ($content as $tab) {
            DB::table('contents')->insert([
                'tabs' => $tab['tabs'],
                'title' => $tab['title'],
                'sub_title' => $tab['sub_title'],
                'description' => $tab['description'],
                'from' => $tab['from'],
                'to' => $tab['to'],
                'link' => $tab['link'],
                'deleted' => $tab['deleted'],
                'updated' => $tab['updated'],
                'list_title' => $tab['list_title'],
            ]);
        }
    }
}
